### PR TITLE
Update ruby version

### PR DESCRIPTION
**Pull request by gssbzn**

### CODE REVIEW

**Review by LSanclemente — APPROVED** [review]
:)

**Comment by carlos-contreras** [comment]
@gssbzn please check the CI ;)

**Comment by gssbzn** [comment]
@miguelperez is anybody maintaining this or should I fork it and maintain it myself?

**Comment by miguelperez** [comment]
Hello. We are but we do not have a direction rigth now. I will add a board to thisnone so we can add the additional festures we have been talking about for months like: templates, docker, heroku.

I will merge this.

**Review by miguelperez — APPROVED** [review]

**Pull request merged**
